-- Script para criar a tabela de vendedores no Supabase

CREATE TABLE IF NOT EXISTS public.vendedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    nome TEXT NOT NULL,
    cpf TEXT NOT NULL,
    identidade TEXT NOT NULL,
    data_nascimento DATE NOT NULL,
    telefone TEXT NOT NULL,
    endereco TEXT NOT NULL,
    bairro TEXT NOT NULL,
    cidade TEXT NOT NULL,
    localizacao TEXT NOT NULL,
    numero_vaga TEXT,
    tipo_instalacao TEXT NOT NULL,
    quantidade_mesas INTEGER,
    produtos_comercializados TEXT[]
);

-- Políticas de Segurança (RLS - Row Level Security)
-- Isso permite que usuários anônimos (do formulário) insiram dados
-- e leiam os dados (para a tela de dashboard/impressão)

ALTER TABLE public.vendedores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir inserção anônima" 
ON public.vendedores 
FOR INSERT 
TO anon 
WITH CHECK (true);

CREATE POLICY "Permitir leitura anônima" 
ON public.vendedores 
FOR SELECT 
TO anon 
USING (true);
